version: '3.3'

volumes:
  dist:

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - /data

  server:
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - '8000:80'
    environment:
      POSTGRES_URL: Server=database;Port=5432;Database=postgres;User Id=postgres;Password=postgres
    restart: on-failure
    depends_on:
      - database
